version: '3.8'

services:
  # PostgreSQL Database - Deploy on EC2 master
  postgres:
    image: postgres:13
    container_name: sarawak-postgres-db
    environment:
      - POSTGRES_DB=visitors
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sarawak2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sarawak-network
    restart: unless-stopped

  # Redis Cache - Deploy on EC2 
  redis:
    image: redis:6
    container_name: sarawak-redis-cache
    ports:
      - "6379:6379"
    networks:
      - sarawak-network
    restart: unless-stopped

  # Verification System - Deploy on worker-node-ec2
  verification-system:
    build: 
      context: ./part1-verification
      dockerfile: Dockerfile
    container_name: sarawak-verification-kiosk
    ports:
      - "5001:5000"
    volumes:
      - ./shared-data:/app/shared-data
      - ./part1-verification/visitor-images:/app/visitor-images
    environment:
      - DATABASE_URL=postgresql://postgres:sarawak2024!@18.143.157.100:5432/visitors
      - JENKINS_URL=http://18.143.157.100:8080
      - ROBOT_SYSTEM_URL=http://18.143.157.100:5003
    depends_on:
      - postgres
    networks:
      - sarawak-network
    restart: unless-stopped

  # Sensor ML System - Deploy on worker (Linux-Docker)
  sensor-ml-system:
    build: 
      context: ./part2-sensor-ml
      dockerfile: Dockerfile
    container_name: sarawak-sensor-ml-pipeline
    ports:
      - "5002:5000"
    volumes:
      - ./shared-data:/app/shared-data
      - ./part2-sensor-ml/sensor-data:/app/sensor-data
      - ./part2-sensor-ml/models:/app/models
    environment:
      - ROBOT_SYSTEM_URL=http://18.143.157.100:5003
      - JENKINS_URL=http://18.143.157.100:8080
    networks:
      - sarawak-network
    restart: unless-stopped

  # Robot System - Deploy on worker-node-ec2
  robot-system:
    build: 
      context: ./part3-robots
      dockerfile: Dockerfile
    container_name: sarawak-robot-controller
    ports:
      - "5003:5000"
    volumes:
      - ./shared-data:/app/shared-data
    environment:
      - JENKINS_URL=http://18.143.157.100:8080
    networks:
      - sarawak-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  sarawak-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
